# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 16:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clases', models.CharField(default='none', editable='false', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Prioritet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioritet', models.CharField(default='normal', editable='false', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(default='open', editable='false', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_description', models.TextField()),
                ('task_author', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task_class', models.ForeignKey(default='none', editable='false', on_delete=django.db.models.deletion.CASCADE, to='TskMng.Clases')),
                ('task_prioritet', models.ForeignKey(default='none', editable='false', on_delete=django.db.models.deletion.CASCADE, to='TskMng.Prioritet')),
                ('task_progress', models.ForeignKey(default='none', editable='false', on_delete=django.db.models.deletion.CASCADE, to='TskMng.Progress')),
            ],
        ),
    ]
