# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 17:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TskMng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clases',
            name='clases',
            field=models.CharField(editable='false', max_length=200),
        ),
        migrations.AlterField(
            model_name='prioritet',
            name='prioritet',
            field=models.CharField(editable='false', max_length=200),
        ),
        migrations.AlterField(
            model_name='progress',
            name='flag',
            field=models.CharField(editable='false', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_class',
            field=models.ForeignKey(editable='false', on_delete=django.db.models.deletion.CASCADE, to='TskMng.Clases'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_prioritet',
            field=models.ForeignKey(editable='false', on_delete=django.db.models.deletion.CASCADE, to='TskMng.Prioritet'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_progress',
            field=models.ForeignKey(editable='false', on_delete=django.db.models.deletion.CASCADE, to='TskMng.Progress'),
        ),
    ]
